/**
 * Liste des pays du monde avec leur indicatif téléphonique international.
 * `code` = ISO alpha-2 (unique), `flag` = emoji drapeau, `dial` = indicatif
 * sans caractères décoratifs (ex. "+33"), `country` = nom en français.
 *
 * Les codes ISO sont uniques ce qui garantit que chaque entrée peut être
 * identifiée sans ambiguïté, même lorsque deux pays partagent le même
 * indicatif (ex. "+1" pour les États-Unis et le Canada).
 */
export type PhoneCountry = {
  code: string;
  country: string;
  flag: string;
  dial: string;
};

export const PHONE_COUNTRIES: PhoneCountry[] = [
  { code: "AF", country: "Afghanistan", flag: "🇦🇫", dial: "+93" },
  { code: "ZA", country: "Afrique du Sud", flag: "🇿🇦", dial: "+27" },
  { code: "AL", country: "Albanie", flag: "🇦🇱", dial: "+355" },
  { code: "DZ", country: "Algérie", flag: "🇩🇿", dial: "+213" },
  { code: "DE", country: "Allemagne", flag: "🇩🇪", dial: "+49" },
  { code: "AD", country: "Andorre", flag: "🇦🇩", dial: "+376" },
  { code: "AO", country: "Angola", flag: "🇦🇴", dial: "+244" },
  { code: "AI", country: "Anguilla", flag: "🇦🇮", dial: "+1264" },
  { code: "AQ", country: "Antarctique", flag: "🇦🇶", dial: "+672" },
  { code: "AG", country: "Antigua-et-Barbuda", flag: "🇦🇬", dial: "+1268" },
  { code: "SA", country: "Arabie saoudite", flag: "🇸🇦", dial: "+966" },
  { code: "AR", country: "Argentine", flag: "🇦🇷", dial: "+54" },
  { code: "AM", country: "Arménie", flag: "🇦🇲", dial: "+374" },
  { code: "AW", country: "Aruba", flag: "🇦🇼", dial: "+297" },
  { code: "AU", country: "Australie", flag: "🇦🇺", dial: "+61" },
  { code: "AT", country: "Autriche", flag: "🇦🇹", dial: "+43" },
  { code: "AZ", country: "Azerbaïdjan", flag: "🇦🇿", dial: "+994" },
  { code: "BS", country: "Bahamas", flag: "🇧🇸", dial: "+1242" },
  { code: "BH", country: "Bahreïn", flag: "🇧🇭", dial: "+973" },
  { code: "BD", country: "Bangladesh", flag: "🇧🇩", dial: "+880" },
  { code: "BB", country: "Barbade", flag: "🇧🇧", dial: "+1246" },
  { code: "BE", country: "Belgique", flag: "🇧🇪", dial: "+32" },
  { code: "BZ", country: "Belize", flag: "🇧🇿", dial: "+501" },
  { code: "BJ", country: "Bénin", flag: "🇧🇯", dial: "+229" },
  { code: "BM", country: "Bermudes", flag: "🇧🇲", dial: "+1441" },
  { code: "BT", country: "Bhoutan", flag: "🇧🇹", dial: "+975" },
  { code: "BY", country: "Biélorussie", flag: "🇧🇾", dial: "+375" },
  { code: "BO", country: "Bolivie", flag: "🇧🇴", dial: "+591" },
  { code: "BA", country: "Bosnie-Herzégovine", flag: "🇧🇦", dial: "+387" },
  { code: "BW", country: "Botswana", flag: "🇧🇼", dial: "+267" },
  { code: "BR", country: "Brésil", flag: "🇧🇷", dial: "+55" },
  { code: "BN", country: "Brunei", flag: "🇧🇳", dial: "+673" },
  { code: "BG", country: "Bulgarie", flag: "🇧🇬", dial: "+359" },
  { code: "BF", country: "Burkina Faso", flag: "🇧🇫", dial: "+226" },
  { code: "BI", country: "Burundi", flag: "🇧🇮", dial: "+257" },
  { code: "KH", country: "Cambodge", flag: "🇰🇭", dial: "+855" },
  { code: "CM", country: "Cameroun", flag: "🇨🇲", dial: "+237" },
  { code: "CA", country: "Canada", flag: "🇨🇦", dial: "+1" },
  { code: "CV", country: "Cap-Vert", flag: "🇨🇻", dial: "+238" },
  { code: "CF", country: "Centrafrique", flag: "🇨🇫", dial: "+236" },
  { code: "CL", country: "Chili", flag: "🇨🇱", dial: "+56" },
  { code: "CN", country: "Chine", flag: "🇨🇳", dial: "+86" },
  { code: "CY", country: "Chypre", flag: "🇨🇾", dial: "+357" },
  { code: "CO", country: "Colombie", flag: "🇨🇴", dial: "+57" },
  { code: "KM", country: "Comores", flag: "🇰🇲", dial: "+269" },
  { code: "CG", country: "Congo", flag: "🇨🇬", dial: "+242" },
  { code: "CD", country: "Congo (RDC)", flag: "🇨🇩", dial: "+243" },
  { code: "KP", country: "Corée du Nord", flag: "🇰🇵", dial: "+850" },
  { code: "KR", country: "Corée du Sud", flag: "🇰🇷", dial: "+82" },
  { code: "CR", country: "Costa Rica", flag: "🇨🇷", dial: "+506" },
  { code: "CI", country: "Côte d'Ivoire", flag: "🇨🇮", dial: "+225" },
  { code: "HR", country: "Croatie", flag: "🇭🇷", dial: "+385" },
  { code: "CU", country: "Cuba", flag: "🇨🇺", dial: "+53" },
  { code: "CW", country: "Curaçao", flag: "🇨🇼", dial: "+599" },
  { code: "DK", country: "Danemark", flag: "🇩🇰", dial: "+45" },
  { code: "DJ", country: "Djibouti", flag: "🇩🇯", dial: "+253" },
  { code: "DM", country: "Dominique", flag: "🇩🇲", dial: "+1767" },
  { code: "EG", country: "Égypte", flag: "🇪🇬", dial: "+20" },
  { code: "SV", country: "El Salvador", flag: "🇸🇻", dial: "+503" },
  { code: "AE", country: "Émirats arabes unis", flag: "🇦🇪", dial: "+971" },
  { code: "EC", country: "Équateur", flag: "🇪🇨", dial: "+593" },
  { code: "ER", country: "Érythrée", flag: "🇪🇷", dial: "+291" },
  { code: "ES", country: "Espagne", flag: "🇪🇸", dial: "+34" },
  { code: "EE", country: "Estonie", flag: "🇪🇪", dial: "+372" },
  { code: "SZ", country: "Eswatini", flag: "🇸🇿", dial: "+268" },
  { code: "US", country: "États-Unis", flag: "🇺🇸", dial: "+1" },
  { code: "ET", country: "Éthiopie", flag: "🇪🇹", dial: "+251" },
  { code: "FJ", country: "Fidji", flag: "🇫🇯", dial: "+679" },
  { code: "FI", country: "Finlande", flag: "🇫🇮", dial: "+358" },
  { code: "FR", country: "France", flag: "🇫🇷", dial: "+33" },
  { code: "GA", country: "Gabon", flag: "🇬🇦", dial: "+241" },
  { code: "GM", country: "Gambie", flag: "🇬🇲", dial: "+220" },
  { code: "GE", country: "Géorgie", flag: "🇬🇪", dial: "+995" },
  { code: "GH", country: "Ghana", flag: "🇬🇭", dial: "+233" },
  { code: "GI", country: "Gibraltar", flag: "🇬🇮", dial: "+350" },
  { code: "GR", country: "Grèce", flag: "🇬🇷", dial: "+30" },
  { code: "GD", country: "Grenade", flag: "🇬🇩", dial: "+1473" },
  { code: "GL", country: "Groenland", flag: "🇬🇱", dial: "+299" },
  { code: "GP", country: "Guadeloupe", flag: "🇬🇵", dial: "+590" },
  { code: "GU", country: "Guam", flag: "🇬🇺", dial: "+1671" },
  { code: "GT", country: "Guatemala", flag: "🇬🇹", dial: "+502" },
  { code: "GG", country: "Guernesey", flag: "🇬🇬", dial: "+44" },
  { code: "GN", country: "Guinée", flag: "🇬🇳", dial: "+224" },
  { code: "GQ", country: "Guinée équatoriale", flag: "🇬🇶", dial: "+240" },
  { code: "GW", country: "Guinée-Bissau", flag: "🇬🇼", dial: "+245" },
  { code: "GY", country: "Guyana", flag: "🇬🇾", dial: "+592" },
  { code: "GF", country: "Guyane française", flag: "🇬🇫", dial: "+594" },
  { code: "HT", country: "Haïti", flag: "🇭🇹", dial: "+509" },
  { code: "HN", country: "Honduras", flag: "🇭🇳", dial: "+504" },
  { code: "HK", country: "Hong Kong", flag: "🇭🇰", dial: "+852" },
  { code: "HU", country: "Hongrie", flag: "🇭🇺", dial: "+36" },
  { code: "BV", country: "Île Bouvet", flag: "🇧🇻", dial: "+47" },
  { code: "CX", country: "Île Christmas", flag: "🇨🇽", dial: "+61" },
  { code: "IM", country: "Île de Man", flag: "🇮🇲", dial: "+44" },
  { code: "NF", country: "Île Norfolk", flag: "🇳🇫", dial: "+672" },
  { code: "AX", country: "Îles Åland", flag: "🇦🇽", dial: "+358" },
  { code: "KY", country: "Îles Caïmans", flag: "🇰🇾", dial: "+1345" },
  { code: "CC", country: "Îles Cocos", flag: "🇨🇨", dial: "+61" },
  { code: "CK", country: "Îles Cook", flag: "🇨🇰", dial: "+682" },
  { code: "FO", country: "Îles Féroé", flag: "🇫🇴", dial: "+298" },
  { code: "FK", country: "Îles Malouines", flag: "🇫🇰", dial: "+500" },
  { code: "MP", country: "Îles Mariannes du Nord", flag: "🇲🇵", dial: "+1670" },
  { code: "MH", country: "Îles Marshall", flag: "🇲🇭", dial: "+692" },
  { code: "SB", country: "Îles Salomon", flag: "🇸🇧", dial: "+677" },
  { code: "TC", country: "Îles Turques-et-Caïques", flag: "🇹🇨", dial: "+1649" },
  { code: "VG", country: "Îles Vierges britanniques", flag: "🇻🇬", dial: "+1284" },
  { code: "VI", country: "Îles Vierges américaines", flag: "🇻🇮", dial: "+1340" },
  { code: "IN", country: "Inde", flag: "🇮🇳", dial: "+91" },
  { code: "ID", country: "Indonésie", flag: "🇮🇩", dial: "+62" },
  { code: "IQ", country: "Irak", flag: "🇮🇶", dial: "+964" },
  { code: "IR", country: "Iran", flag: "🇮🇷", dial: "+98" },
  { code: "IE", country: "Irlande", flag: "🇮🇪", dial: "+353" },
  { code: "IS", country: "Islande", flag: "🇮🇸", dial: "+354" },
  { code: "IL", country: "Israël", flag: "🇮🇱", dial: "+972" },
  { code: "IT", country: "Italie", flag: "🇮🇹", dial: "+39" },
  { code: "JM", country: "Jamaïque", flag: "🇯🇲", dial: "+1876" },
  { code: "JP", country: "Japon", flag: "🇯🇵", dial: "+81" },
  { code: "JE", country: "Jersey", flag: "🇯🇪", dial: "+44" },
  { code: "JO", country: "Jordanie", flag: "🇯🇴", dial: "+962" },
  { code: "KZ", country: "Kazakhstan", flag: "🇰🇿", dial: "+7" },
  { code: "KE", country: "Kenya", flag: "🇰🇪", dial: "+254" },
  { code: "KG", country: "Kirghizistan", flag: "🇰🇬", dial: "+996" },
  { code: "KI", country: "Kiribati", flag: "🇰🇮", dial: "+686" },
  { code: "XK", country: "Kosovo", flag: "🇽🇰", dial: "+383" },
  { code: "KW", country: "Koweït", flag: "🇰🇼", dial: "+965" },
  { code: "RE", country: "La Réunion", flag: "🇷🇪", dial: "+262" },
  { code: "LA", country: "Laos", flag: "🇱🇦", dial: "+856" },
  { code: "LS", country: "Lesotho", flag: "🇱🇸", dial: "+266" },
  { code: "LV", country: "Lettonie", flag: "🇱🇻", dial: "+371" },
  { code: "LB", country: "Liban", flag: "🇱🇧", dial: "+961" },
  { code: "LR", country: "Libéria", flag: "🇱🇷", dial: "+231" },
  { code: "LY", country: "Libye", flag: "🇱🇾", dial: "+218" },
  { code: "LI", country: "Liechtenstein", flag: "🇱🇮", dial: "+423" },
  { code: "LT", country: "Lituanie", flag: "🇱🇹", dial: "+370" },
  { code: "LU", country: "Luxembourg", flag: "🇱🇺", dial: "+352" },
  { code: "MO", country: "Macao", flag: "🇲🇴", dial: "+853" },
  { code: "MK", country: "Macédoine du Nord", flag: "🇲🇰", dial: "+389" },
  { code: "MG", country: "Madagascar", flag: "🇲🇬", dial: "+261" },
  { code: "MY", country: "Malaisie", flag: "🇲🇾", dial: "+60" },
  { code: "MW", country: "Malawi", flag: "🇲🇼", dial: "+265" },
  { code: "MV", country: "Maldives", flag: "🇲🇻", dial: "+960" },
  { code: "ML", country: "Mali", flag: "🇲🇱", dial: "+223" },
  { code: "MT", country: "Malte", flag: "🇲🇹", dial: "+356" },
  { code: "MA", country: "Maroc", flag: "🇲🇦", dial: "+212" },
  { code: "MQ", country: "Martinique", flag: "🇲🇶", dial: "+596" },
  { code: "MU", country: "Maurice", flag: "🇲🇺", dial: "+230" },
  { code: "MR", country: "Mauritanie", flag: "🇲🇷", dial: "+222" },
  { code: "YT", country: "Mayotte", flag: "🇾🇹", dial: "+262" },
  { code: "MX", country: "Mexique", flag: "🇲🇽", dial: "+52" },
  { code: "FM", country: "Micronésie", flag: "🇫🇲", dial: "+691" },
  { code: "MD", country: "Moldavie", flag: "🇲🇩", dial: "+373" },
  { code: "MC", country: "Monaco", flag: "🇲🇨", dial: "+377" },
  { code: "MN", country: "Mongolie", flag: "🇲🇳", dial: "+976" },
  { code: "ME", country: "Monténégro", flag: "🇲🇪", dial: "+382" },
  { code: "MS", country: "Montserrat", flag: "🇲🇸", dial: "+1664" },
  { code: "MZ", country: "Mozambique", flag: "🇲🇿", dial: "+258" },
  { code: "MM", country: "Myanmar", flag: "🇲🇲", dial: "+95" },
  { code: "NA", country: "Namibie", flag: "🇳🇦", dial: "+264" },
  { code: "NR", country: "Nauru", flag: "🇳🇷", dial: "+674" },
  { code: "NP", country: "Népal", flag: "🇳🇵", dial: "+977" },
  { code: "NI", country: "Nicaragua", flag: "🇳🇮", dial: "+505" },
  { code: "NE", country: "Niger", flag: "🇳🇪", dial: "+227" },
  { code: "NG", country: "Nigéria", flag: "🇳🇬", dial: "+234" },
  { code: "NU", country: "Niue", flag: "🇳🇺", dial: "+683" },
  { code: "NO", country: "Norvège", flag: "🇳🇴", dial: "+47" },
  { code: "NC", country: "Nouvelle-Calédonie", flag: "🇳🇨", dial: "+687" },
  { code: "NZ", country: "Nouvelle-Zélande", flag: "🇳🇿", dial: "+64" },
  { code: "OM", country: "Oman", flag: "🇴🇲", dial: "+968" },
  { code: "UG", country: "Ouganda", flag: "🇺🇬", dial: "+256" },
  { code: "UZ", country: "Ouzbékistan", flag: "🇺🇿", dial: "+998" },
  { code: "PK", country: "Pakistan", flag: "🇵🇰", dial: "+92" },
  { code: "PW", country: "Palaos", flag: "🇵🇼", dial: "+680" },
  { code: "PS", country: "Palestine", flag: "🇵🇸", dial: "+970" },
  { code: "PA", country: "Panama", flag: "🇵🇦", dial: "+507" },
  { code: "PG", country: "Papouasie-Nouvelle-Guinée", flag: "🇵🇬", dial: "+675" },
  { code: "PY", country: "Paraguay", flag: "🇵🇾", dial: "+595" },
  { code: "NL", country: "Pays-Bas", flag: "🇳🇱", dial: "+31" },
  { code: "BQ", country: "Pays-Bas caribéens", flag: "🇧🇶", dial: "+599" },
  { code: "PE", country: "Pérou", flag: "🇵🇪", dial: "+51" },
  { code: "PH", country: "Philippines", flag: "🇵🇭", dial: "+63" },
  { code: "PN", country: "Pitcairn", flag: "🇵🇳", dial: "+64" },
  { code: "PL", country: "Pologne", flag: "🇵🇱", dial: "+48" },
  { code: "PF", country: "Polynésie française", flag: "🇵🇫", dial: "+689" },
  { code: "PR", country: "Porto Rico", flag: "🇵🇷", dial: "+1787" },
  { code: "PT", country: "Portugal", flag: "🇵🇹", dial: "+351" },
  { code: "QA", country: "Qatar", flag: "🇶🇦", dial: "+974" },
  { code: "DO", country: "République dominicaine", flag: "🇩🇴", dial: "+1809" },
  { code: "RO", country: "Roumanie", flag: "🇷🇴", dial: "+40" },
  { code: "GB", country: "Royaume-Uni", flag: "🇬🇧", dial: "+44" },
  { code: "RU", country: "Russie", flag: "🇷🇺", dial: "+7" },
  { code: "RW", country: "Rwanda", flag: "🇷🇼", dial: "+250" },
  { code: "EH", country: "Sahara occidental", flag: "🇪🇭", dial: "+212" },
  { code: "BL", country: "Saint-Barthélemy", flag: "🇧🇱", dial: "+590" },
  { code: "KN", country: "Saint-Christophe-et-Niévès", flag: "🇰🇳", dial: "+1869" },
  { code: "SM", country: "Saint-Marin", flag: "🇸🇲", dial: "+378" },
  { code: "MF", country: "Saint-Martin (partie française)", flag: "🇲🇫", dial: "+590" },
  { code: "SX", country: "Saint-Martin (partie néerlandaise)", flag: "🇸🇽", dial: "+1721" },
  { code: "PM", country: "Saint-Pierre-et-Miquelon", flag: "🇵🇲", dial: "+508" },
  { code: "VC", country: "Saint-Vincent-et-les-Grenadines", flag: "🇻🇨", dial: "+1784" },
  { code: "SH", country: "Sainte-Hélène", flag: "🇸🇭", dial: "+290" },
  { code: "LC", country: "Sainte-Lucie", flag: "🇱🇨", dial: "+1758" },
  { code: "WS", country: "Samoa", flag: "🇼🇸", dial: "+685" },
  { code: "AS", country: "Samoa américaines", flag: "🇦🇸", dial: "+1684" },
  { code: "ST", country: "Sao Tomé-et-Principe", flag: "🇸🇹", dial: "+239" },
  { code: "SN", country: "Sénégal", flag: "🇸🇳", dial: "+221" },
  { code: "RS", country: "Serbie", flag: "🇷🇸", dial: "+381" },
  { code: "SC", country: "Seychelles", flag: "🇸🇨", dial: "+248" },
  { code: "SL", country: "Sierra Leone", flag: "🇸🇱", dial: "+232" },
  { code: "SG", country: "Singapour", flag: "🇸🇬", dial: "+65" },
  { code: "SK", country: "Slovaquie", flag: "🇸🇰", dial: "+421" },
  { code: "SI", country: "Slovénie", flag: "🇸🇮", dial: "+386" },
  { code: "SO", country: "Somalie", flag: "🇸🇴", dial: "+252" },
  { code: "SD", country: "Soudan", flag: "🇸🇩", dial: "+249" },
  { code: "SS", country: "Soudan du Sud", flag: "🇸🇸", dial: "+211" },
  { code: "LK", country: "Sri Lanka", flag: "🇱🇰", dial: "+94" },
  { code: "SE", country: "Suède", flag: "🇸🇪", dial: "+46" },
  { code: "CH", country: "Suisse", flag: "🇨🇭", dial: "+41" },
  { code: "SR", country: "Suriname", flag: "🇸🇷", dial: "+597" },
  { code: "SJ", country: "Svalbard et Jan Mayen", flag: "🇸🇯", dial: "+47" },
  { code: "SY", country: "Syrie", flag: "🇸🇾", dial: "+963" },
  { code: "TJ", country: "Tadjikistan", flag: "🇹🇯", dial: "+992" },
  { code: "TW", country: "Taïwan", flag: "🇹🇼", dial: "+886" },
  { code: "TZ", country: "Tanzanie", flag: "🇹🇿", dial: "+255" },
  { code: "TD", country: "Tchad", flag: "🇹🇩", dial: "+235" },
  { code: "CZ", country: "Tchéquie", flag: "🇨🇿", dial: "+420" },
  { code: "TH", country: "Thaïlande", flag: "🇹🇭", dial: "+66" },
  { code: "TL", country: "Timor oriental", flag: "🇹🇱", dial: "+670" },
  { code: "TG", country: "Togo", flag: "🇹🇬", dial: "+228" },
  { code: "TK", country: "Tokelau", flag: "🇹🇰", dial: "+690" },
  { code: "TO", country: "Tonga", flag: "🇹🇴", dial: "+676" },
  { code: "TT", country: "Trinité-et-Tobago", flag: "🇹🇹", dial: "+1868" },
  { code: "TN", country: "Tunisie", flag: "🇹🇳", dial: "+216" },
  { code: "TM", country: "Turkménistan", flag: "🇹🇲", dial: "+993" },
  { code: "TR", country: "Turquie", flag: "🇹🇷", dial: "+90" },
  { code: "TV", country: "Tuvalu", flag: "🇹🇻", dial: "+688" },
  { code: "UA", country: "Ukraine", flag: "🇺🇦", dial: "+380" },
  { code: "UY", country: "Uruguay", flag: "🇺🇾", dial: "+598" },
  { code: "VU", country: "Vanuatu", flag: "🇻🇺", dial: "+678" },
  { code: "VA", country: "Vatican", flag: "🇻🇦", dial: "+379" },
  { code: "VE", country: "Venezuela", flag: "🇻🇪", dial: "+58" },
  { code: "VN", country: "Viêt Nam", flag: "🇻🇳", dial: "+84" },
  { code: "WF", country: "Wallis-et-Futuna", flag: "🇼🇫", dial: "+681" },
  { code: "YE", country: "Yémen", flag: "🇾🇪", dial: "+967" },
  { code: "ZM", country: "Zambie", flag: "🇿🇲", dial: "+260" },
  { code: "ZW", country: "Zimbabwe", flag: "🇿🇼", dial: "+263" },
];

/**
 * Normalise une chaîne pour une comparaison insensible à la casse et aux
 * accents (pratique pour filtrer la recherche d'un pays).
 */
export function normalizeForSearch(value: string): string {
  return value
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "");
}

export function findPhoneCountry(code: string): PhoneCountry | undefined {
  return PHONE_COUNTRIES.find((option) => option.code === code);
}
